### ISSUE TITLE
Uploading .hccap doesn't work properly

### ISSUE THREAD

**Issue by Speedi13** [vnik5287/Crackq#4]
`f = open(_content, 'r')`
The file opening flags in line 177 should be changed to `'rb'` to be able to read hccap files correctly.

**Comment by vnik5287** [comment]
Thanks for reporting this! It is indeed a bug. Most of our users are on posix systems where 'r' implies 'rb' and this issue was never reported. I'm assuming you're running it on Windows (8.1 or 10)? We're working on version 0.4 at the moment after the complete infrastructure redesign. This version should incorporate the fix.

**Comment by vnik5287** [comment]
v0.4 is out
